#!/usr/bin/env python3
"""spectrogram.py: Utilities for dealing with spectrograms"""
import warnings
import os

from librosa import ParameterError
import scipy
import numpy as np
import librosa.filters
import skimage.transform
from PIL import Image
import torch
import matplotlib
from matplotlib import pyplot as plt
import matplotlib.colors
import torch.nn.functional as F
import torchaudio

from opensoundscape.audio import Audio
from opensoundscape.utils import min_max_scale, linear_scale


class Spectrogram:
    """Class storing spectrogram values and metadata

    Can be initialized directly from spectrogram, frequency, and time values or created from an
    Audio object using the .from_audio() method.

    To initialize from the linear-valued power spectrogram or the raw STFT values,
    pass the `power_spectrogram` or `magnitude` arguments to the constructor, and pass
    `spectrogram=None`. Regardless of which input method is used, the stored attribute
    self.power_spectrogram will always be the linear-valued power spectrogram, and
    self.spectrogram property will return the decibel-valued power spectrogram.

    Note: the spectrogram is defined as the absolute square of the
    short-time Fourier transform (STFT) of the audio signal [1]. The attribute
    self.power_spectrogram will always be the linear-valued power spectrogram
    (i.e. abs(stft)**2). You can also retrieve the
    magnitude of the STFT via the self.magnitude property (which takes the
    square root of self.spectrogram), or the decibel-valued power via
    self.spectrogram (which computes 10*log10(self.power_spectrogram)).

    Attributes:
        power_spectrogram: (np.ndarray) 2d array of power spectrogram (not dB-scaled)
        frequencies: (list) discrete frequency bins generated by fft
        times: (list) time from beginning of file to the center of each window
        window_samples: number of samples per window when spec was created
            [default: None]
        overlap_samples: number of samples overlapped in consecutive windows
            when spec was created [default: None]
        window_type: window fn used to make spectrogram, eg 'hann'
            [default: None]
        audio_sample_rate: sample rate of audio from which spec was created
            [default: None]

    Properties:
        spectrogram: returns the dB-valued power spectrogram
        magnitude: returns the linear-valued STFT magnitude (sqrt(self.power_spectrogram))
        shape: returns the shape of the spectrogram array as (n_frequencies, n_times)
        duration: returns the duration of the audio signal in seconds
        window_length_seconds: length of a single fft window, in seconds
        window_hop_seconds: time difference (sec) between consecutive windows' centers
    """

    __slots__ = (
        "frequencies",
        "times",
        "power_spectrogram",
        "window_samples",
        "hop_samples",
        "audio_sample_rate",
        "fft_size",
    )

    def __init__(
        self,
        spectrogram,
        frequencies,
        times,
        power_spectrogram=None,
        stft=None,
        window_samples=None,
        hop_samples=None,
        audio_sample_rate=None,
        fft_size=None,
    ):

        if not isinstance(frequencies, np.ndarray):
            raise TypeError(
                f"Spectrogram.frequencies should be an np.ndarray [shape=(n,)]. "
                f"Got {frequencies.__class__}"
            )
        if not isinstance(times, np.ndarray):
            raise TypeError(
                f"Spectrogram.times should be an np.ndarray [shape=(m,)]. "
                f"Got {times.__class__}"
            )
        if frequencies.ndim != 1:
            raise TypeError(
                f"frequencies should be an np.ndarray [shape=(n,)]. "
                f"Got {frequencies.shape}"
            )
        if times.ndim != 1:
            raise TypeError(
                f"times should be an np.ndarray [shape=(m,)]. " f"Got {times.shape}"
            )

        if spectrogram is not None:
            _check_shape_and_type(spectrogram, frequencies, times)
            power_spectrogram = 10 ** (spectrogram / 10)
        elif power_spectrogram is not None:
            assert stft is None, "Cannot specify both power_spectrogram and magnitude"
            assert (
                spectrogram is None
            ), "Cannot specify spectrogram when providing power_spectrogram or magnitude"
            _check_shape_and_type(power_spectrogram, frequencies, times)
        elif stft is not None:
            assert (
                spectrogram is None
            ), "Cannot specify spectrogram when providing power_spectrogram or magnitude"
            _check_shape_and_type(stft, frequencies, times)
            power_spectrogram = np.abs(stft) ** 2

        self.power_spectrogram = power_spectrogram
        self.frequencies = frequencies
        self.times = times
        self.window_samples = window_samples
        self.hop_samples = hop_samples
        self.audio_sample_rate = audio_sample_rate
        self.fft_size = window_samples if fft_size is None else fft_size

    @property
    def spectrogram(self):
        """returns the dB-valued power spectrogram"""
        return 10 * np.log10(self.power_spectrogram + 1e-10)

    @property
    def magnitude(self):
        """returns the linear-valued STFT magnitude (sqrt(self.power_spectrogram))"""
        return np.sqrt(self.power_spectrogram)

    @property
    def rms(self):
        """calculate time-windowed amplitude ie ~rms~ (see NOTE for caveats)

        NOTE: the computed values will only be equivalent to the rms of the original signal
        if the spectrogram was created with a rectangular window, e.g.

        ```python
        Spectrogram.from_audio(audio, window_fn=torch.ones).rms
        ```

        (see https://github.com/librosa/librosa/issues/1795 for details)

        Returns:
            np.ndarray: time-windowed amplitude measurement
        """
        assert (
            self.window_samples is not None and self.fft_size is not None
        ), """Cannot compute rms without knowing window_samples and fft_size used to
          create spectrogram. Make sure self.window_samples and self.fft_size are not None."""

        power = self.power_spectrogram

        # Adjust the DC and sr/2 Nyquist frequency components
        power[..., 0, :] *= 0.5
        if self.fft_size % 2 == 0:
            power[..., -1, :] *= 0.5

        # Calculate power time series by summing over each frame
        power = 2 * np.sum(power, axis=-2, keepdims=False) / self.window_samples

        # Take the square root to get RMS (amplitude, not power)
        return np.sqrt(power)

    @classmethod
    def from_audio(
        cls,
        audio,
        window_samples=None,
        window_length_sec=None,
        hop_samples=None,
        overlap_fraction=None,
        fft_size=None,
        **kwargs,
    ):
        """
        create a Spectrogram object from an Audio object

        Note: the spectrogram is defined as the absolute square of the short-time Fourier transform
        (STFT) of the audio signal [1]. The attribute self.power_spectrogram will always be the
        linear-valued power spectrogram (i.e. abs(stft)**2). You can also retrieve the magnitude of
        the STFT via the self.magnitude property (which takes the square root of
        self.power_spectrogram), or the decibel-valued power via self.spectrogram (which computes
        10*log10(self.power_spectrogram)).

        Args:
            audio: Audio object
            window_samples: number of audio samples per spectrogram window (pixel)
                - Defaults to 512 if window_samples and window_length_sec are None
                - Note: cannot specify both window_samples and window_length_sec
            window_length_sec: length of a single window in seconds
                - Note: cannot specify both window_samples and window_length_sec
                - Warning: specifying this parameter often results in less efficient
                    spectrogram computation because window_samples will not be
                    a power of 2.
            hop_samples: number of samples between the start of consecutive windows
                - Note: must not specify both hop_samples and overlap_fraction
            overlap_fraction: fractional temporal overlap between consecutive windows
                - Defaults to 0.5 if hop_samples and overlap_fraction are None
                - Note: cannot specify both hop_samples and overlap_fraction
            fft_size: number of fft points, see torchaudio.transforms.Spectrogram
                If None, defaults to window_samples

            **kwargs: kwargs are passed to torchaudio.transforms.Spectrogram

        Returns:
            opensoundscape.spectrogram.Spectrogram object


        ### Notes on spectrogram creation:
        We use torchaudio.transforms.Spectrogram to create the STFT power spectrogram, then normalize
        by window length to preserve time-domain signal norm (ie similar values regardless of
        window size parameter).
        This formulation is equilvalent to librosa.magphase(librosa.stft(x,...),power=2)/window_length.
        Scipy returns spec/window_length, while librosa and torchaudio do not normalize by the window length.
        A result equivalen to librosa or torchaudio can be obtained via self.power_spectrogram * self.window_samples.
        Scipy also detrends frame-by-frame by default, resulting in ~0 energy in 0 Hz bin.

        ### Notes on recovering rms amplitude from spectrogram:
        To recover a windowed signal RMS from a spectrogram, use window_fn=torch.ones
        then use the self.rms property to calculate windowed RMS amplitude.

        ```python
        spec = Spectrogram.from_audio(audio, window_fn=torch.ones)
        rms = spec.rms
        # similar to:
        # S=librosa.magphase(librosa.stft(audio.samples, window=np.ones, center=False,
        #   win_length=w,n_fft=w,hop_length=w//2))[0]
        # rms = librosa.feature.rms(S=S, frame_length=w)
        ```

        [1] Karlheinz Gröchenig: “Foundations of Time-Frequency Analysis”, Birkhäuser Boston 2001,
        DOI:10.1007/978-1-4612-0003-1
        """

        if not isinstance(audio, Audio):
            raise TypeError("Class method expects Audio class as input")

        # determine window_samples
        if window_samples is not None and window_length_sec is not None:
            raise ValueError(
                "You may not specify both `window_samples` and `window_length_sec`"
            )
        elif window_samples is None and window_length_sec is None:
            window_samples = 512  # defaults to 512 samples
        elif window_length_sec is not None:
            window_samples = int(audio.sample_rate * window_length_sec)
        # else: use user-provided window_samples argument

        # determine hop_samples
        if hop_samples is not None and overlap_fraction is not None:
            raise ValueError(
                "You may not specify both `hop_samples` and `overlap_fraction`"
            )
        elif hop_samples is None and overlap_fraction is None:
            # default is 50% overlap
            hop_samples = window_samples // 2
        elif overlap_fraction is not None:
            assert (
                overlap_fraction >= 0 and overlap_fraction < 1
            ), "overlap_fraction must be >=0 and <1"
            hop_samples = int(window_samples * (1 - overlap_fraction))
        # else: use the provided hop_samples argument

        # create the spectrogram 2d array using torchaudio
        to_spec = torchaudio.transforms.Spectrogram(
            n_fft=window_samples if fft_size is None else fft_size,
            win_length=window_samples,
            hop_length=hop_samples,
            power=2,
            center=False,  # True zero-pads first and last windows centered on signal start/end
            **kwargs,
        )
        spectrogram = to_spec(torch.tensor(audio.samples))

        # rescale by window length to preserve time norm
        # this results in approximately consistent values across window sizes
        # and matches scipy's default behavior, but is not the default for librosa or torchaudio
        # note: in general, normalize by window_samples** (power / 2), but we use power=2 here
        spectrogram = spectrogram / window_samples

        # Compute frequency and time vectors associated with the 2d array

        # because we used center=True, the times correspond to the center of each window
        window_len = float(window_samples) / audio.sample_rate
        hop_len = float(hop_samples) / audio.sample_rate
        center_times = np.arange(spectrogram.shape[-1]) * hop_len + window_len / 2

        # frequency bins will start at 0 and end at sr/2 if n is even, or sr/2-sr/n if n is odd
        # the frequency value always represents the "center" of the bin for a Fourier transform
        frequencies = (
            np.arange(0, to_spec.n_fft // 2 + 1) * audio.sample_rate / to_spec.n_fft
        )

        return cls(
            spectrogram=None,
            power_spectrogram=spectrogram.numpy(),
            frequencies=frequencies,
            times=center_times,
            window_samples=window_samples,
            hop_samples=hop_samples,
            audio_sample_rate=audio.sample_rate,
            fft_size=window_samples if fft_size is None else fft_size,
        )

    def __repr__(self):
        return (
            f"<Spectrogram(spectrogram={self.power_spectrogram.shape}, "
            f"frequencies={self.frequencies.shape}, times={self.times.shape})>"
        )

    @property
    def shape(self):
        """returns the shape of the spectrogram array as (n_frequencies, n_times)"""
        return self.power_spectrogram.shape

    @property
    def duration(self):
        """returns the duration of the audio signal in seconds

        Note: can be shorter than the audio signal it was created from,
        depending on the window and hop sizes used to create the spectrogram.
        """
        if self.window_length_seconds:
            return self.times[-1] - self.times[0] + self.window_length_seconds
        else:
            return None

    @property
    def window_length_seconds(self):
        """calculate length of a single fft window, in seconds:"""
        if self.window_samples and self.audio_sample_rate:
            return float(self.window_samples) / self.audio_sample_rate
        return None

    @property
    def window_hop_seconds(self):
        """calculate time difference (sec) between consecutive windows' centers"""
        if self.hop_samples and self.audio_sample_rate:
            return float(self.hop_samples) / self.audio_sample_rate
        return None

    def min_max_scale(self, feature_range=(0, 1)):
        """
        Linearly rescale spectrogram values to a range of values using
        in_range as minimum and maximum

        Args:
            feature_range: tuple of (low,high) values for output

        Returns:
            Spectrogram object with values rescaled to feature_range
        """

        if len(feature_range) != 2:
            raise AttributeError(
                f"`feature_range` must have 2 elements (min, max). Got {feature_range}"
            )
        if feature_range[1] < feature_range[0]:
            raise AttributeError(
                f"`feature_range` must have 2nd value >= 1st. Got {feature_range}"
            )

        # use self.__class__ so that child classes can inherit this method
        return self._spawn(
            spectrogram=min_max_scale(self.spectrogram, feature_range=feature_range)
        )

    def linear_scale(self, feature_range=(0, 1), input_range=(-100, -20)):
        """
        Linearly rescale spectrogram values to a range of values


        Args:
            feature_range: tuple of (low,high) values for output
            input_range: tuple of (min,max) range. values beyond this range
                will be clipped to (low,high) before mapping onto the feature_range
        Returns:
            Spectrogram object with values rescaled to feature_range
        """

        if len(input_range) != 2:
            raise AttributeError(
                f"`input_range` must have 2 elements (min, max). Got {input_range}"
            )
        if len(feature_range) != 2:
            raise AttributeError(
                f"`feature_range` must have 2 elements (min, max). Got {feature_range}"
            )
        if feature_range[1] < feature_range[0]:
            raise AttributeError(
                f"`feature_range` must have 2nd value >= 1st. Got {feature_range}"
            )

        return self._spawn(
            spectrogram=linear_scale(
                self.spectrogram, in_range=input_range, out_range=feature_range
            )
        )

    def limit_range(self, min=-100, max=-20):
        """Limit (clip) the values of the spectrogram to range from min to max

        values of self.spectrogram less than min are set to min
        values of self.spectrogram greater than max are set to max

        similar to Audacity's gain and range parameters

        Args:
            min: values lower than this are set to this
            max: values higher than this are set to this

        Returns:
            Spectrogram object with .spectrogram values clipped to (min,max)
        """
        if max <= min:
            raise ValueError(
                f"max_db must be greater than min_db (got min={min} and max={max})"
            )

        return self._spawn(spectrogram=self.spectrogram.clip(min, max))

    def bandpass(self, min_f, max_f, out_of_bounds_ok=True):
        """extract a frequency band from a spectrogram

        crops the 2-d array of the spectrograms to the desired frequency range
        by removing rows.

        Lowest and highest row kept are those with frequencies closest to min_f and max_f


        Args:
            min_f: low frequency in Hz for bandpass
            max_f: high frequency in Hz for bandpass
            out_of_bounds_ok: (bool) if False, raises ValueError if min_f or max_f
                are not within the range of the original spectrogram's frequencies
                [default: True]

        Returns:
            bandpassed spectrogram object

        """

        if min_f >= max_f:
            raise ValueError(
                f"min_f must be less than max_f (got min_f {min_f}, max_f {max_f}"
            )

        if not out_of_bounds_ok:
            # self.frequencies fully coveres the spec's frequency range
            if min_f < min(self.frequencies) or max_f > max(self.frequencies):
                raise ValueError(
                    "with out_of_bounds_ok=False, min_f and max_f must fall"
                    "inside the range of self.frequencies"
                )

        # find indices of the frequencies in spec_freq closest to min_f and max_f
        lowest_index = np.abs(self.frequencies - min_f).argmin()
        highest_index = np.abs(self.frequencies - max_f).argmin()

        # take slices of the spectrogram and spec_freq that fall within desired range
        return self._spawn(
            power_spectrogram=self.power_spectrogram[
                lowest_index : highest_index + 1, :
            ],
            frequencies=self.frequencies[lowest_index : highest_index + 1],
        )

    def trim(self, start_time, end_time):
        """extract a time segment from a spectrogram

        first and last columns kept are those with times closest to start_time and end_time

        Args:
            start_time: in seconds
            end_time: in seconds

        Returns:
            spectrogram object from extracted time segment

        """

        # find indices of the times in self.times closest to min_t and max_t
        lowest_index = np.abs(self.times - start_time).argmin()
        highest_index = np.abs(self.times - end_time).argmin()

        # take slices of the spectrogram and spec_freq that fall within desired range
        return self._spawn(
            power_spectrogram=self.power_spectrogram[
                :, lowest_index : highest_index + 1
            ],
            times=self.times[lowest_index : highest_index + 1],
        )

    def plot(
        self,
        ax=None,
        show_colorbar=False,
        range=(-80, 0),
        kHz=False,
        cmap="Greys",
    ):
        """
        Plot a spectrogram (e.g., mel) with evenly sized pixels and *evenly spaced y-ticks*,
        where tick labels show the corresponding nonlinear frequency values.

        Args:
            ax (matplotlib.axes.Axes, optional): Axis to plot on.
            show_colorbar (bool): Include a colorbar.
            range (tuple): (min, max) dB range for color normalization.
            kHz (bool): Plot y-axis in kHz instead of Hz.
            cmap (str): Colormap to use for the spectrogram.

        Returns:
            matplotlib.axes.Axes
        """
        if ax is None:
            fig, ax = plt.subplots()

        norm = matplotlib.colors.Normalize(vmin=range[0], vmax=range[1])
        freqs = self.frequencies / (1000 if kHz else 1)

        # Plot: pixels evenly spaced vertically
        im = ax.pcolormesh(
            self.times,
            freqs,
            self.spectrogram,
            norm=norm,
            cmap=cmap,
        )

        ax.set_ylabel(f"Frequency ({'kHz' if kHz else 'Hz'})")
        ax.set_xlabel("Time (s)")

        if show_colorbar:
            plt.colorbar(im, ax=ax)

        return ax

    def amplitude(self, dB=False):
        """removed in favor of .rms property"""
        raise AttributeError(
            "Spectrogram.amplitude() has been removed. Use the .rms property instead."
        )

    def net_amplitude(self, signal_band, reject_bands=None):
        """create RMS amplitude signal in signal_band and subtract amplitude from reject_bands

        rescale the signal and reject bands by dividing by their bandwidths in Hz
        (amplitude of each reject_band is divided by the total bandwidth of all reject_bands.
        amplitude of signal_band is divided by bandwidth of signal_band. )

        Args:
            signal_band: [low,high] frequency range in Hz (positive contribution)
            reject band: list of [low,high] frequency ranges in Hz (negative contribution)

        return: time-series array of net amplitude"""

        # find the amplitude signal for the desired frequency band
        f_low, f_high = signal_band
        signal_band_amplitude = self.bandpass(f_low, f_high).rms
        signal_band_bandwidth = f_high - f_low
        # normalize by frequency bandwidth
        net_amplitude = signal_band_amplitude / signal_band_bandwidth

        # then subtract the energy in the the reject_bands from the
        # signal_band_amplitude to get net_amplitude
        if not (reject_bands is None):
            # we sum up the sizes of the rejection bands (to not overweight signal_band)
            reject_bands = np.array(reject_bands)
            reject_bands_total_bandwidth = sum(reject_bands[:, 1] - reject_bands[:, 0])

            # subtract reject_band_amplitude
            for reject_band in reject_bands:
                f_low, f_high = reject_band
                reject_band_amplitude = self.bandpass(f_low, f_high).rms
                net_amplitude = net_amplitude - (
                    reject_band_amplitude / reject_bands_total_bandwidth
                )

            # negative signal shouldn't be kept, because it means reject was
            # stronger than signal. Zero it:
            net_amplitude = np.maximum(net_amplitude, 0)

        return net_amplitude

    def to_image(
        self,
        shape=None,
        channels=1,
        colormap=None,
        invert=False,
        return_type="pil",
        range=(-80, 0),
        use_skimage=False,
    ):
        """Create an image from spectrogram (array, tensor, or PIL.Image)

        Note: Linearly rescales values in the spectrogram from
        `range` (min,max) to [0,255] (PIL.Image) or [0,1] (array/tensor)

        Default of `range` is [-80, 0], so, e.g.,
        0 db is loudest -> black, -80 db is quietest -> white

        Args:
            shape: tuple of output dimensions as (height, width)
                - if None, retains original shape of self.spectrogram
                - if first or second value are None, retains original shape in that dimension
            channels: eg 3 for rgb, 1 for greyscale
                - must be 3 to use colormap
            colormap:
                if None, greyscale spectrogram is generated
                Can be any matplotlib colormap name such as 'jet'
            return_type: type of returned object
                - 'pil': PIL.Image
                - 'np': numpy.ndarray
                - 'torch': torch.tensor
            range: tuple of (min,max) values of .spectrogram to map to the lowest/highest
                pixel values. Values outside this range will be clipped to the min/max values
            use_skimage: if True, use skimage.transform.resize to resize the image
                [default: False] is recommended and 10-100x faster, but True can be used
                to match the behavior of OpenSoundscape <0.11.0
        Returns:
            Image/array with type depending on `return_type`:
            - PIL.Image with c channels and shape w,h given by `shape`
                and values in [0,255]
            - np.ndarray with shape [c,h,w] and values in [0,1]
            - or torch.tensor with shape [c,h,w] and values in [0,1]
        """
        assert return_type in [
            "pil",
            "np",
            "torch",
        ], f"Arg `return_type` must be one of 'pil', 'np', 'torch'. Got {return_type}."
        if colormap is not None:
            # it doesn't make sense to use a colormap with #channels != 3
            assert (
                channels == 3
            ), f"Channels must be 3 to use colormap. Specified {channels}"

        # rescale spec_range to [1, 0]
        # note the low values represent silence, so a silent img would be black
        # if plotted directly from these values.
        array = linear_scale(self.spectrogram, in_range=range, out_range=(0, 1))

        # clip values to [0,1]
        array = np.clip(array, 0, 1)

        # flip up-down so that frequency increases from bottom to top
        array = array[::-1, :]

        # invert if desired
        if invert:
            array = 1 - array

        # apply colormaps
        if colormap is not None:  # apply a colormap to get RGB channels
            cm = matplotlib.pyplot.get_cmap(colormap)
            array = cm(array)[..., :3]  # remove alpha channel (4)

        # determine output height and width
        if shape is None:  # if None, use original shape
            shape = np.shape(array)
        else:
            # if height or width are None, use original sizes
            if shape[0] is None:
                shape[0] = np.shape(array)[0]
            if shape[1] is None:
                shape[1] = np.shape(array)[1]

        if use_skimage:
            # match legacy behavior of OpenSoundscape <0.11.0
            # skimage is 10-100x slower than torch
            image = skimage.transform.resize(array, (shape[0], shape[1], channels))
            image = torch.Tensor(image)
            if len(image.shape) == 2:  # add channel dim to front
                image = image.unsqueeze(0)
            else:  # move channel dim to front
                image = image.permute(2, 0, 1)
        else:
            # use torch, much faster than skimage

            # make tensor; copy to avoid an error about -1 stride
            tensor = torch.Tensor(array.copy())

            if len(tensor.shape) == 2:  # add channel dim to front
                tensor = tensor.unsqueeze(0)
            else:  # move channel dim to front
                tensor = tensor.permute(2, 0, 1)
            # add batch dim
            tensor = tensor.unsqueeze(0)

            # copy over channel dimension if needed
            tensor = tensor.expand(-1, channels, -1, -1)

            # interpolate to desired shape
            image = F.interpolate(
                tensor,
                size=(shape[0], shape[1]),
                mode="bilinear",
                align_corners=False,
            )
            image = image.squeeze(0)  # remove leading batch dim

        if return_type == "np":
            image = image.numpy()
        elif return_type == "pil":
            # reshape c,h,w to h,w,c
            image = image.permute(1, 2, 0).numpy()

            if image.shape[-1] == 1:
                # PIL doesnt like [x,y,1] shape, it wants [x,y] instead
                # if there's only one channel
                image = image[:, :, 0]
            # expected shape of input is [h,w,c]
            image = Image.fromarray(np.uint8(image * 255))

        return image

    def _spawn(self, **kwargs):
        """return copy of object, replacing any desired fields from __slots__

        pass any desired updates as kwargs
        """
        assert np.all(
            [k in self.__slots__ or k in ("spectrogram", "stft") for k in kwargs.keys()]
        ), (
            "only pass members of Spectrogram.__slots__ to _spawn as kwargs! "
            f"slots: {self.__slots__}"
        )
        # load the current values from each __slots__ key
        slots = {key: self.__getattribute__(key) for key in self.__slots__}
        # update any user-specified values
        slots.update(kwargs)

        if not "spectrogram" in slots:
            # required arg, but usually initialized from power_spectrogram
            slots["spectrogram"] = None
        # create new instance of the class
        return self.__class__(**slots)


class MelSpectrogram(Spectrogram):
    """Immutable mel-spectrogram container

    A mel spectrogram is a spectrogram with pseudo-logarithmically spaced
    frequency bins (see literature) rather than linearly spaced bins.

    See Spectrogram class an Librosa's melspectrogram for detailed documentation.

    NOTE: Here we rely on scipy's spectrogram function (via Spectrogram)
    rather than on librosa's _spectrogram or melspectrogram, because the
    amplitude of librosa's spectrograms do not match expectations. We only
    use the mel frequency bank from Librosa.
    """

    def __repr__(self):
        return (
            f"<MelSpectrogram(spectrogram={self.power_spectrogram.shape}, "
            "frequencies={self.frequencies.shape}, times={self.times.shape})>"
        )

    @classmethod  # TODO use torchaudio's MelSpectrogram
    def from_audio(
        cls,
        audio,
        window_samples=None,
        window_length_sec=None,
        hop_samples=None,
        overlap_fraction=None,
        n_fft=None,
        dB_scale=True,
        n_mels=64,
        f_min=0,
        f_max=None,
        norm=None,  # None or 'slaney'
        mel_scale="htk",  # or "slaney"
        **kwargs,
    ):
        """Create a MelSpectrogram object from an Audio object

        First creates a spectrogram and a mel-frequency filter bank,
        then computes the dot product of the filter bank with the spectrogram.

        A Mel spectrogram is a spectrogram with a quasi-logarithmic frequency
        axis that has often been used in language processing and other domains.

        The kwargs for the mel frequency bank are documented at:
        - https://librosa.org/doc/latest/generated/librosa.feature.melspectrogram.html#librosa.feature.melspectrogram
        - https://librosa.org/doc/latest/generated/librosa.filters.mel.html?librosa.filters.mel

        Args:
            audio: Audio object
            window_type="hann": see scipy.signal.spectrogram docs for description
            window_samples: number of audio samples per spectrogram window (pixel)
                - Defaults to 512 if window_samples and window_length_sec are None
                - Note: cannot specify both window_samples and window_length_sec
            window_length_sec: length of a single window in seconds
                - Note: cannot specify both window_samples and window_length_sec
            hop_samples: number of samples between consecutive windows
                - Note: cannot specify both hop_samples and overlap_fraction
            overlap_fraction: fractional temporal overlap between consecutive windows
                - Defaults to 0.5 if hop_samples and overlap_fraction are None
                - Note: cannot specify both hop_samples and overlap_fraction
            n_fft: see scipy.signal.spectrogram's `nfft` parameter
            dB_scale: If True, rescales values to decibels
            n_mels: Number of mel bands to generate [default: 128]
                Note: n_mels should be chosen for compatibility with the
                Spectrogram parameter `window_samples`. Choosing a value
                `> ~ window_samples/10` will result in zero-valued rows while
                small values blend rows from the original spectrogram.
            power: Exponent for the magnitude spectrogram [default: 2]
            f_min: lowest frequency (in Hz) represented in the mel spectrogram
                [default: 0]
            f_max: highest frequency (in Hz) represented in the mel spectrogram
                [default: sr/2]
            norm: if 'slaney', divide the triangular mel weights by the width of the mel band
                (area normalization). None otherwise. See librosa or torchaudio docs.
                [default: None]
            mel_scale: 'htk' [default] or 'slaney'
                slaney: use Slaney-style mel-filter bank
                htk: use HTK-style mel-filter bank

        Returns:
            opensoundscape.spectrogram.MelSpectrogram object
        """
        if f_max is None:
            f_max = audio.sample_rate / 2

        if not isinstance(audio, Audio):
            raise TypeError("Class method expects Audio class as input")

        # Initialize spectrogram object with linear frequencies
        spec = super().from_audio(
            audio,
            window_samples=window_samples,
            window_length_sec=window_length_sec,
            hop_samples=hop_samples,
            overlap_fraction=overlap_fraction,
            fft_size=n_fft,
            **kwargs,
        )

        # perform mel transform on the spectrogram
        mel_transform = torchaudio.transforms.MelScale(
            n_mels=n_mels,
            sample_rate=audio.sample_rate,
            f_min=f_min,
            f_max=f_max,
            n_stft=spec.fft_size // 2 + 1,
            mel_scale=mel_scale,
            norm=norm,
        )
        # we apply filterbank on the power_spectrogram (not the dB-scaled spectrogram)
        spec.power_spectrogram = mel_transform(
            torch.tensor(spec.power_spectrogram)
        ).numpy()

        # Calculate mel frequency bins
        spec.frequencies = librosa.filters.mel_frequencies(
            n_mels=n_mels, fmin=f_min, fmax=f_max, htk=(mel_scale == "htk")
        )

        return spec

    def plot(
        self, ax=None, show_colorbar=False, range=(-80, 0), kHz=False, n_freq_ticks=5
    ):
        """
        Plot a spectrogram (e.g., mel) with evenly sized pixels and *evenly spaced y-ticks*,
        where tick labels show the corresponding nonlinear frequency values.

        Args:
            ax (matplotlib.axes.Axes, optional): Axis to plot on.
            show_colorbar (bool): Include a colorbar.
            range (tuple): (min, max) dB range for color normalization.
            kHz (bool): Plot y-axis in kHz instead of Hz.
            n_freq_ticks (int): number of y-axis ticks to display

        Returns:
            matplotlib.axes.Axes
        """
        if ax is None:
            fig, ax = plt.subplots()

        norm = matplotlib.colors.Normalize(vmin=range[0], vmax=range[1])
        freqs = self.frequencies / (1000 if kHz else 1)
        n_freqs, n_times = self.power_spectrogram.shape

        # Plot: pixels evenly spaced vertically
        im = ax.imshow(
            self.spectrogram,  # dB-scaled power spectrogram
            origin="lower",
            aspect="auto",
            extent=[self.times[0], self.times[-1], 0, n_freqs],
            cmap="Greys",
            norm=norm,
        )

        # --- Evenly spaced y ticks in visual space ---
        y_positions = np.linspace(0, n_freqs - 1, n_freq_ticks)

        # Interpolate the *frequency values* corresponding to those y positions
        freq_labels = np.interp(y_positions, np.arange(n_freqs), freqs)

        ax.set_yticks(y_positions)
        if kHz:
            ax.set_yticklabels([f"{f:.2f}" for f in freq_labels])
        else:
            ax.set_yticklabels([f"{f:.0f}" for f in freq_labels])

        ax.set_ylabel(f"Frequency ({'kHz' if kHz else 'Hz'})")
        ax.set_xlabel("Time (s)")

        if show_colorbar:
            plt.colorbar(im, ax=ax)

        return ax


def plot_spectrograms(
    specs, n_col=3, value_range=(-80, 0), frequency_range=None, titles=None
):
    """plot a grid of spectrograms

    Args:
        specs: list of Spectrogram objects
        n_col: number of columns in the plot grid
        value_range: (min, max) value range for plotting
        titles: optional list of titles for each subplot

    Returns:
        fig, axs: matplotlib figure and axes objects
    """
    if frequency_range is not None:
        specs = [s.bandpass(frequency_range[0], frequency_range[1]) for s in specs]
    n_row = int(np.ceil(len(specs) / n_col))
    fig, axs = plt.subplots(n_row, n_col, figsize=(5 * n_col, 3 * n_row))
    for i, s in enumerate(specs):
        r = i // n_col
        c = i % n_col
        ax = axs[r, c] if n_row > 1 else axs[c]
        s.plot(ax=ax, range=value_range)
        if titles:
            ax.set_title(titles[i])
    for j in range(i + 1, n_row * n_col):
        r = j // n_col
        c = j % n_col
        ax = axs[r, c] if n_row > 1 else axs[c]
        ax.axis("off")
    plt.tight_layout()

    return fig, axs


def plot_spectrograms_from_audio(
    audio_clips,
    n_col=3,
    value_range=(-80, 0),
    frequency_range=None,
    titles=None,
    **kwargs,
):
    """create spectrograms from audio clips and plot them in a grid

    Args:
        audio_clips: list of Audio objects
        n_col: number of columns in the plot grid
        value_range: (min, max) value range for plotting
        titles: optional list of titles for each subplot
        **kwargs: kwargs passed to Spectrogram.from_audio

    Returns:
        fig, axs: matplotlib figure and axes objects
    """
    specs = [Spectrogram.from_audio(a, **kwargs) for a in audio_clips]
    return plot_spectrograms(
        specs,
        n_col=n_col,
        value_range=value_range,
        frequency_range=frequency_range,
        titles=titles,
    )


def torch_to_dB(spectrogram, power=2, eps=1e-10):
    assert power in (1, 2), "power must be 1 or 2 to convert to dB scale"
    factor = 20 if power == 1 else 10
    return factor * torch.log10(spectrogram.clamp(min=eps))


def numpy_to_dB(spectrogram, power=2, eps=1e-10):
    assert power in (1, 2), "power must be 1 or 2 to convert to dB scale"
    factor = 20 if power == 1 else 10
    return factor * np.log10(np.clip(spectrogram, a_min=eps, a_max=None))


def _check_shape_and_type(spec_input, frequencies, times):
    if not isinstance(spec_input, np.ndarray):
        raise TypeError(
            f"spectrogram should be a np.ndarray [shape=(n, m)]. "
            f"Got {spec_input.__class__}"
        )
    if spec_input.ndim != 2:
        raise TypeError(
            f"spectrogram should be a np.ndarray [shape=(n, m)]. "
            f"Got {spec_input.shape}"
        )
    if spec_input.shape != (frequencies.shape[0], times.shape[0]):
        raise TypeError(
            f"Dimension mismatch, spectrogram.shape: {spec_input.shape}, "
            f"frequencies.shape: {frequencies.shape}, times.shape: {times.shape}"
        )
